config/routes.rb
Db3::Application.routes.draw do
  
  devise_for :users

  resources :challenges
  resources :users

  get "welcome/index"
  root :to => 'welcome#index'
  match 'users/:id/change_role/:role' => 'users#changeRole', :as => :change_role
  match 'challenges/:id/getzip(.:format)' => 'challenges#getstream', :as => :zip_challenge
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  attr_accessible :first_name, :last_name, :organization, :work_id, :role

  has_many :challenges, :dependent => :destroy
  # attr_accessible :title, :body
  def admin?
    return  read_attribute(:role) == 'admin'
  end

  def moderator?
    return  read_attribute(:role) == 'moderator'
  end

  def organizer?
    return  read_attribute(:role) == 'organizer'
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	#Cancan filter
	load_and_authorize_resource

  def index
    @users = User.all
  end

	# def show
	# 	@user = User.find(params[:id])
	# end

  def changeRole
    @user = User.find(params[:id])
    @user.role = params[:role]

    if ['organizer', 'moderator'].include? params[:role] and @user.save
      flash[:notice] = "User '#{@user.email}' has been made #{params[:role]}"
    else
      flash[:error] = "Can't change role"  
    end

    redirect_to users_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy 
    flash[:notice] = "User '#{@user.email}' deleted."
    redirect_to users_path
  end

  
end

app/views/users/_user_table.html.erb
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr> 
      <th>User ID</th> 
      <th>Email</th>
      <th>Work Bench ID</th> 
      <th>First Name</th> 
      <th>Last Name</th> 
      <th>Role</th> 
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td> <%= user.id %> </td>
        <td> <%= user.email %> </td>
        <td> <%= user.work_id %> </td>
        <td> <%= user.first_name %> </td>
        <td> <%= user.last_name %> </td>
        <td> <%= user.role %> </td>
        <% if @current_user.admin? %>
          <td>
            <%= link_to "", change_role_path(:id => user.id, :role => 'moderator'), :class => "icon-user", :TITLE => "Promote user to a moderator", :id => "make_mod_" + user.id.to_s %>
          </td>
        <% end %>
        <!-- <td> <%= link_to '', user, :class => "icon-user", :TITLE => "Promote user to Mod"%> </td> -->
        <td> <%= link_to '', edit_user_registration_path(user),:id => "edit_" + user.id.to_s, :class => "icon-wrench", :TITLE => "Show/Edit user" %> </td>
        <td> <%= link_to '', user, :confirm => 'Are you sure?', :method => :delete, :id => "delete_" + user.id.to_s, :class => "icon-trash", :TITLE => "Delete user" %> </td>
        <!-- <A HREF="http://www.yourdomain.com/" TITLE="Your text description">Your Text</A> -->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_user_table_for_mod.html.haml
%table{:class => "table table-striped table-bordered table-condensed"}
  %thead
    %tr
      %th User ID
      %th Email
      %th Work Bench ID
      %th First Name
      %th Last Name
  %tbody
    - @users.each do |user|
      %tr
        %td= user.id
        %td= user.email
        %td= user.work_id
        %td= user.first_name
        %td= user.last_name
        %td= link_to "Show", user
        %td= link_to "Edit", edit_user_registration_path(user),:id => "edit_" + user.id.to_s
        %td= link_to "Delete", user, :confirm => 'Are you sure?', :method => :delete, :id => "delete_" + user.id.to_s

app/views/users/index.html.erb
<h3>Welcome back, <%= current_user.first_name %> <%= current_user.last_name %></h3>
<h4>Here are all the users</h4>

<%= render :partial => 'user_table' %>