config/routes.rb
Db3::Application.routes.draw do
  
  devise_for :users

  resources :challenges
  resources :users

  get "welcome/index"
  root :to => 'welcome#index'
  match 'users/:id/change_role/:role' => 'users#changeRole', :as => :change_role
  match 'challenges/:id/getzip(.:format)' => 'challenges#getstream', :as => :zip_challenge
  

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  attr_accessible :description, :end_time, :start_time, :title, :yamlformat, :webpages_attributes, :phrases_attributes, :user_id, :timestamps
  has_many :webpages, :dependent => :destroy
  has_many :phrases, :dependent => :destroy
  belongs_to :user
  accepts_nested_attributes_for :webpages, :allow_destroy => true
  accepts_nested_attributes_for :phrases, :allow_destroy => true

  def getTmpFilePath
    return "#{Rails.root}/zip_tmp/"
  end

  def getTmpZipName
    return 'tmp'+ self.id.to_s + '.zip'
  end

  def getTmpYmlName
    return 'tmp' + self.id.to_s + '.yml'
  end

  def getyaml_hash
    #Creating yaml hash
    yaml_hash = Hash.new()
    self.attributes.each do |attr_name, attr_value|
    	yaml_hash[attr_name] = attr_value
    end

    #Prepare webpage for
    yaml_html = Hash.new()
    self.webpages.each do |webpage|
    	yaml_html[webpage.title] = webpage.webpage_yaml if webpage.title != ""
    end
    yaml_hash["html"] = yaml_html

    #Prepare phase hash for yaml file
    yaml_phase = Hash.new()
    self.phrases.each_with_index do |phrase, index|
    	yaml_phase[index+1] = phrase.phase_yaml if phrase.label != ""
    end
    yaml_hash["phase"] = yaml_phase

    return yaml_hash
  end

  def appendWebpage(webpage,zipfile)
   if not webpage.title.empty?
        html_name = webpage.title + '.html'
        File.open(self.getTmpFilePath + html_name, "w+") do |file|
                file.write(webpage.web_content)
        end

        #Add each html to zip
        zipfile.add(html_name,self.getTmpFilePath + html_name)
        #A file is added
        return true
    end

    #No file is added
    return false
  end

  def appendFiletoZip
    #Creating html and zip files
    Zip::File.open(self.getTmpFilePath + self.getTmpZipName,Zip::File::CREATE) do |zipfile|
      self.webpages.each do |webpage|
        self.appendWebpage(webpage,zipfile)
      end
      #Add yml to the zip
      zipfile.add(self.getTmpYmlName,self.getTmpFilePath + self.getTmpYmlName)
    end
  end

  def createZip
    yaml_hash = self.getyaml_hash

    #Create yaml file
    File.open(self.getTmpFilePath + self.getTmpYmlName, "w+") do |file|
      file.write(yaml_hash.to_yaml)
    end

    #Append all yaml and html files to zip
    self.appendFiletoZip

    return self.getTmpFilePath + self.getTmpZipName
  end

  def tempCleanUp
    #Path parameters
    zip_path = self.getTmpFilePath + 'tmp'+ self.id.to_s + '.zip'
    yaml_path = self.getTmpFilePath + 'tmp' + self.id.to_s + '.yml'

    #Delete html files
    self.webpages.each do |webpage|
      if not webpage.title.empty?
        html_name = webpage.title + '.html'
        File.delete(self.getTmpFilePath + html_name)
      end
    end

    File.delete(zip_path) #Delete zip file
    File.delete(yaml_path) #Delete yaml file
  end

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
	require 'zip'

	#Cancan filter
	load_and_authorize_resource
	
	def index
		valid_list = ['title', 'start_time', 'end_time', nil]
		if current_user.admin? || current_user.moderator?
			@challenges = Challenge.find(:all,:order => params[:sort]) if valid_list.include? params[:sort]
		else
			@challenges = Challenge.all(:conditions => {:user_id => current_user.id},:order => params[:sort]) if valid_list.include? params[:sort]
		end
	end

    def getstream
        #Challenge
        challenge = Challenge.find_by_id(params[:id])

        #Create zip file
        zip_path = challenge.createZip

    	#Sending zip
	    zip_file = File.read(zip_path)
	    send_data zip_file, :filename => challenge.title + '.zip', :x_sendfile => true
        
        #Data clean up
        challenge.tempCleanUp
    end


	def new
		@challenge = Challenge.new
		12.times {@challenge.webpages.build}
		3.times do
			phrase = @challenge.phrases.build
			3.times {phrase.tasks.build}	
		end
	end

	def edit
		@challenge = Challenge.find(params[:id])
	end

	def show
		@challenge = Challenge.find(params[:id])
	end

	def create
		@challenge = Challenge.new(params[:challenge])
		if @challenge.save
			flash[:notice] = "Successfully created '#{@challenge.title}' challenge"
			redirect_to @challenge
		else 
			render :action => 'new'
		end
	end

	def update
		@challenge = Challenge.find(params[:id])
		if @challenge.update_attributes(params[:challenge])
			flash[:notice] = "Successfully updated '#{@challenge.title}' challenge"
			redirect_to @challenge
		else
			render :action => 'edit'
		end
	end

	def destroy
		@challenge = Challenge.find(params[:id])
		@challenge.destroy 
		flash[:notice] = "Challenge '#{@challenge.title}' deleted."
		redirect_to challenges_path
	end
end

app/views/challenges/_challenge_table.html.haml
%table{:class => "table table-striped table-bordered table-condensed"}
  %thead
    %tr
      %th= link_to 'Title', challenges_path(:sort => 'title')
      %th Description
      %th= link_to 'Start Time', challenges_path(:sort => 'start_time')
      %th= link_to 'End Time', challenges_path(:sort => 'end_time')
      %th= link_to 'Last Updated', challenges_path(:sort => 'updated_at')
  %tbody
    - @challenges.each do |challenge|
      %tr
        %td= challenge.title 
        %td= challenge.description
        %td= challenge.start_time.try(:strftime, "%d/%b/%Y")
        %td= challenge.end_time.try(:strftime, "%d/%b/%Y")
        %td= challenge.updated_at.try(:strftime, "%d/%b/%Y")
        %td= link_to '', challenge, :class => "icon-picture", :title => "Show challenge"
        %td= link_to '', edit_challenge_path(challenge), :class => "icon-wrench", :id => "edit_" + challenge.id.to_s, :title => "Edit challenge"
        %td= link_to '', zip_challenge_path(:id => challenge.id), :class => "icon-download dl_zip", :id => "zip_" + challenge.id.to_s, :title => "Download challenge"
        %td= link_to '', challenge, :class => "icon-trash", :confirm => 'Are you sure?', :method => :delete, :id => "delete_" + challenge.id.to_s, :title => "Delete challenge"

app/views/challenges/_challenge_table_for_mod.html.haml
%table{:class => "table table-striped table-bordered table-condensed"}
  %thead
    %tr
      %th= link_to 'Title', challenges_path(:sort => 'title')
      %th Description
      %th= link_to 'Start Time', challenges_path(:sort => 'start_time')
      %th= link_to 'End Time', challenges_path(:sort => 'end_time')
      %th= link_to 'Last Updated', challenges_path(:sort => 'updated_at')
  %tbody
    - @challenges.each do |challenge|
      %tr
        %td= challenge.title 
        %td= challenge.description
        %td= challenge.start_time.strftime("%d/%b/%Y")
        %td= challenge.end_time.strftime("%d/%b/%Y")
        %td= challenge.updated_at.strftime("%d/%b/%Y")
        %td= link_to "Show", challenge
        %td= link_to "Edit", edit_challenge_path(challenge),:id => "edit_" + challenge.id.to_s
        %td= link_to "Zip", zip_challenge_path(:id => challenge.id)
        %td= link_to "Delete", challenge, :confirm => 'Are you sure?', :method => :delete, :id => "delete_" + challenge.id.to_s

app/views/challenges/_challenge_table_for_user.html.haml
%table{:class => "table table-striped table-bordered table-condensed"}
  %thead
    %tr
      %th Title
      %th Description
      %th Start Time
      %th End Time
      %th Last Updated
  %tbody
    - @challenges.each do |challenge|
      %tr
        %td= challenge.title 
        %td= challenge.description
        %td= challenge.start_time
        %td= challenge.end_time
        %td= challenge.updated_at
        %td= link_to "Show", challenge
        %td= link_to "Edit", edit_challenge_path(challenge),:id => "edit_" + challenge.id.to_s
        %td= link_to "Zip", zip_challenge_path(:id => challenge.id)
        %td= link_to "Delete", challenge, :confirm => 'Are you sure?', :method => :delete, :id => "delete_" + challenge.id.to_s

app/views/challenges/_form.html.erb
<%= form_for @challenge do |f| %>
    <div id="content">
        <ul id="pills" class="nav nav-pills" data-pills="pills">
            <li class="active"><a href="#basic_info" data-toggle="pill"><i class="icon-wrench"></i> Basic Information</a></li>
            <li><a href="#webpages" data-toggle="pill"><i class="icon-list-alt"></i> Webpages</a></li>
            <li><a href="#phases" data-toggle="pill"><i class="icon-list"></i> Phases</a></li>
            <li><a href="#submit" data-toggle="pill"><i class="icon-check"></i> Submit</a></li>
        </ul>
    </div>
    <div id="my-pill-content" class="pill-content">
        <div class="pill-pane active" id="basic_info">
            <p>
                <%= f.label :title %>
                <%= f.text_field :title %><br/>
                <% if @challenge.start_time == nil or @challenge.end_time == nil %>
                    <%= f.label :start_time %>
                    <%= f.text_field :start_time, :class => "datepicker" %><br/>
                    <%= f.label :end_time %>
                    <%= f.text_field :end_time, :class => "datepicker" %><br/>
                <% else %>
                    <%= f.label :start_time %>
                    <%= f.text_field :start_time, :class => "datepicker", :value => @challenge.start_time.strftime("%d/%B/%Y") %><br/>
                    <%= f.label :end_time %>
                    <%= f.text_field :end_time, :class => "datepicker", :value => @challenge.end_time.strftime("%d/%B/%Y") %><br/>
                <% end %>
                <%= f.label :description %>
                <%= f.text_area :description, :style => "width: 800px; height: 200px" %><br/>
                <%= f.hidden_field :user_id, :value => current_user.id %>
            </p>
        </div>
        <div class="pill-pane" id="webpages">
            <p>    
                <% i = 0 %>
                <%= f.fields_for :webpages do |builder| %>
                    <% if i == 0 %>
                        <div id="<%= i %>">
                            <%= render 'webpage_fields', :f => builder %>
                            <a class="btn2_<%= i + 1 %>">Add a Page</a>
                            </br>
                        </div>
                    <% else %>
                        <%= content_tag :div, id: i do -%>
                            <%= render 'webpage_fields', :f => builder %>
                            <a class="btn2_<%= i + 1 %>">Add a Page</a>
                            </br>
                        <% end -%>
                        <script>
                            if(!document.getElementById('challenge_webpages_attributes_<%= i %>_title').value) {
                                $( "#<%= i %>" ).hide();
                            }
                        </script>
                    <% end %>
                    <script>
                        $(document).ready(function(){
                            $(".btn1_<%= i %>").click(function(){
                                $( "#<%= i %>" ).hide();
                                $(".btn2_<%= i %>").show()
                            });
                            $(".btn2_<%= i %>").click(function(){
                                $( "#<%= i %>" ).show();
                                $(".btn2_<%= i %>").hide()
                            });
                        });
                    </script>
                    <% i = i + 1 %>
                <% end %>
            </p>
        </div>
        <div class="pill-pane" id="phases">
            <p>    
                <% j = 0 %>
                <a class="phrase_btn2_<%= j %>">Add a Phase</a>
                <%= f.fields_for :phrases do |builder| %>
                   <div id="phrase_<%= j %>">
                        <%= render 'phrase_fields', :f => builder %>
                        <a class="phrase_btn2_<%= j + 1 %>">Add a Phase</a>
                        </br>
                   </div>
                   <script>
                       if(!document.getElementById('challenge_phrases_attributes_<%= j %>_label').value) {
                            $( "#phrase_<%= j %>" ).hide();
                        }
                   </script>
                   <script>
                        $(document).ready(function(){
                            $(".phrase_btn1_<%= j %>").click(function(){
                                $( "#phrase_<%= j %>" ).hide();
                                $(".phrase_btn2_<%= j %>").show();
                            });
                            $(".phrase_btn2_<%= j %>").click(function(){
                                $( "#phrase_<%= j %>" ).show();
                                $(".phrase_btn2_<%= j %>").hide();
                            });
                        });
                    </script>
                   <% j = j + 1 %>
                <% end %>
                <br>
            </p>
        </div>
        <div class="pill-pane" id="submit">
            <p><%= f.submit "Submit" , :id => "submit", :class => "btn btn-primary" %></p>
        </div>
    </div>
<% end %>

app/views/challenges/_phrase_fields.html.erb
<div>
	<%= f.label :label, "Label" %>
	<%= f.text_field :label %>

	<% if false %> 
		<% if @phrase.start_date == nil or @phrase.end_date == nil %>
			<%= f.label :start_date, "Start date" %> 
			<%= f.text_field :start_date, :class => "datepicker" %>
			<%= f.label :end_date, "End date" %>
			<%= f.text_field :end_date, :class => "datepicker" %>
		<% else %>
			<%= f.label :start_date, "Start date" %> 
			<%= f.text_field :start_date, :class => "datepicker", :value => @phrase.start_date.strftime("%d/%B/%Y") %>
			<%= f.label :end_date, "End date" %>
			<%= f.text_field :end_date, :class => "datepicker", :value => @phrase.end_date.strftime("%d/%B/%Y") %>
		<% end %>
	<% end %> 

	<%= f.label :start_date, "Start date" %> 
	<%= f.text_field :start_date, :class => "datepicker" %>
	<%= f.label :end_date, "End date" %>
	<%= f.text_field :end_date, :class => "datepicker" %>

	<%= f.label :max_submissions, "Maximum submissions" %>
	<%= f.text_field :max_submissions %>

	<%= f.label :submissions_per_day, "Number of submissions in one day" %>
	<%= f.text_field :submissions_per_day %>

	<%= f.label :task_averaging, "Task averaging" %>
	<%= f.text_field :task_averaging %>

	<%= f.label :numeric_format, "Number of decimals in leaderboard" %>
	<%= f.text_field :numeric_format %> 

	<%= link_to_function "Add a Task", "addTask_base(this)" %>
	<%= f.fields_for :tasks do |builder| %>
		<%= render 'task_fields', :f => builder %>
	<% end %>
</div>

app/views/challenges/_task_fields.html.erb
<div class="task">	
	<div class="span12">
		<%= f.label :name, "Task name" %> 
		<%= f.text_field :name %>

		<%= f.label :url, "URL" %>
		<%= f.text_field :url %>

		<%= f.label :description, "Task Description" %>
		<%= f.text_area :description, :style => "width: 800px; height: 200px" %>
		</br>
		<%= link_to_function "Add a Task", "addTask(this)" %>
	</div>
</div>

app/views/challenges/_webpage_fields.html.erb
<div class="webpage">
	
	<%= f.label :title, "Page Title"%>
	<%= f.text_field :title %><br/>

	<div class="ext_url"> Use external URL <%= f.check_box :is_external_url, :onclick => "checkStatus(this)", :class => "urlcheckbox"%> </div>

	<div class="text_wysithml5">	
		<%= f.label :web_content, "Page Content" %>
		<%= f.text_area :web_content, :style => "width: 800px; height: 200px", :class => "wysihtml5" , :rows => 10 %>
	</div> 

	<div class="text_simple_box"> 
		<%= f.label :url, "External URL"%>
		<%= f.text_field :url%>
	</div> 

	<div class="destroy"> Remove this page from the challenge
		<%= f.check_box :_destroy %> 
	</div>
</div>

app/views/challenges/edit.html.erb
<div class="span12">
	<%= render :partial => 'form' %>
</div>

app/views/challenges/getstream.html.erb
<%= @test %>

app/views/challenges/index.html.erb
<% if user_signed_in? %>
	<h3>Welcome back, <%= current_user.first_name %> <%= current_user.last_name %></h3>
	<% if current_user.admin? or current_user.moderator? %>
		<h4>All challenges listed here</h4>
	<% else %>
		<h4>Here are your challenges</h4>
	<% end %>

	<%= render :partial => 'challenge_table' %>

	<%= link_to "New Challenge", new_challenge_path %>

	<% else %>
	<h3>Welcome guest, register or sign in to view your challenges</h3>
<% end %>

app/views/challenges/mychallenges.html.erb
<h3>Welcome back, <%= current_user.first_name %> <%= current_user.last_name %></h3>
<h4>Here are your challenges</h4>

<%= render :partial => 'challenge_table_for_user' %>

<%= link_to "New Challenge", new_challenge_path %>

app/views/challenges/new.html.erb
<%= render :partial => 'form' %>

<%= link_to "List all challenges", challenges_path %>

<div class="container">

app/views/challenges/publicchallenges.html.erb
<h3>Welcome back, <%= current_user.first_name %> <%= current_user.last_name %></h3>
<h4>Here are the public challenges</h4>

<table class="table table-striped table-bordered table-condensed">
	<tr>
		<th>Title</th>
		<th>Short Description</th>
		<th>Due Date</th>
		<th>Created date</th>
		<th>Last updated</th>
	</tr>
	<% for challenge in @challenges %>
		<tr>
			<td><%= challenge.title %></td>
			<td><%= challenge.description %></td>
			<td><%= challenge.end_time %></td>
			<td><%= challenge.created_at %></td>
			<td><%= challenge.updated_at %></td>
			<td><%= link_to "Show", challenge %></td>
			<td><%= link_to "Edit", edit_challenge_path(challenge),:id => "edit_" + challenge.id.to_s%></td>
			<td><%= link_to "Delete", challenge, :confirm => 'Are you sure?', :method => :delete, :id => "delete_" + challenge.id.to_s%> </td>
		</tr>
	<% end %> 
</table>

app/views/challenges/show.html.erb
<% if @challenge.title != "" %>
  <strong> Challenge Name: </strong><%= @challenge.title %> </br>
<% end %>
<br>
<ul>
<% for webpage in @challenge.webpages %>
  <% if webpage.title != "" %>
    <li>
    	<strong> Title: </strong> <%= webpage.title %> </br>
    	<% if webpage.is_external_url? %>
  	     <strong> External URL: </strong> <%= webpage.url %>
      <% else %>
  	     <strong> Content: </strong> <%= webpage.web_content %>
     	<% end %>
    </li>
  <% end %>

<% end %>
<br>
<% @challenge.phrases.each_with_index do |phase, index| %>
  <% if phase.label != "" %>
      <li>
        <strong> Phase <%= index + 1%>: </strong>  <%= phase.label %> </br>
      </li>
   <% end %>
<% end %>
</ul>





<p>
  <%= link_to "Edit", edit_challenge_path(@challenge) %> |
  <%= link_to "Delete", @challenge, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", challenges_path %>
</p>