config/routes.rb
Db3::Application.routes.draw do
  
  devise_for :users

  resources :challenges
  resources :users

  get "welcome/index"
  root :to => 'welcome#index'
  match 'users/:id/change_role/:role' => 'users#changeRole', :as => :change_role
  match 'challenges/:id/getzip(.:format)' => 'challenges#getstream', :as => :zip_challenge
  

end

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'ChaLearn', root_path%></li>
</ul>

<!--Push everything in this class to the right of navbar-->
<ul class="nav pull-right">
	<!--Logged in case -->
	<% if user_signed_in? %>

	<!--Admin case/Mod case-->
    <% if current_user.admin? || current_user.moderator? %>
    <li><%= link_to 'Manage Challenges', challenges_path %></li>
    <li><%= link_to 'Manage Users', users_path %></li>

    <!--Normal user case-->
    <% else %>
  	<li><%= link_to 'Wizard', new_challenge_path %></li>
  	<li><%= link_to 'My Challenges', challenges_path %></li>
  	<% end %>
  	
  	<div class="btn-group">
	  <a class="btn btn-info" href="#"><i class="icon-user icon-white"></i><%= " " + current_user.email %></a>
	  <a class="btn btn-info dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret white-caret"></span></a>

	  <ul class="dropdown-menu">
  	<ul><i class="icon-pencil"></i><%= link_to ' Edit', edit_user_registration_path %></ul>
	<ul><i class="icon-trash"></i><%= link_to ' Sign Out', destroy_user_session_path, :method => :delete%></ul>
	  </ul>

	</div>

	<!--Not logged in case-->
	<% else %>
	<!--Register Button-->
	<li><%= link_to 'Register', new_user_registration_path %></li>
	<!--Sign in Dropdown-->
	<li class="dropdown">
	  <a class="dropdown-toggle" href="#" data-toggle="dropdown">Sign In<strong class="caret"></strong></a>
	  
	  <div class="dropdown-menu" style="padding: 10px;">
	  <%= form_for("user", :url => user_session_path) do |f| %>

		  <div class="control-group" style="margin-bottom: -5px; margin-top: 10px;">
		    <div class="controls">
		    <!-- Email -->
		    <%= f.text_field :email, :placeholder => "Email", :id => 'drop_user_email' %>
		    <!-- Password -->
		    <%= f.password_field :password, :placeholder => "Password" , :id => 'drop_user_password' %>
		    </div>
		  </div>

    	<div class = "checkbox inline">
    		<%= f.check_box :remember_me %> <%= f.label :remember_me %>
    	</div>
		  <li style="margin-top: 0px; margin-bottom: 10px;"><%= f.submit 'Sign in' , :id => 'drop_sign_in', :class => "btn btn-success"%></li>
		  <li><%= link_to "Forgot your password?", new_password_path('user') %></li>
	  <% end %>
	  </div>
	</li>

	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <title><%= content_for?(:title) ? yield(:title) : "ChaLearn" %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
</head>
  <body>
    <%# application layout styled for Twitter Bootstrap 2.3 %>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <% if flash[:notice] %>
                <div class="alert alert-success"><%= flash[:notice] %></div> 
              <% end %>
              <% if flash[:error] %>
                <div class="alert alert-danger"><%= flash[:error] %></div> 
              <% end %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>

</body>
<script>
$.backstretch("http://i452.photobucket.com/albums/qq249/Banziilloic/1397323_10151752159127327_238511333_o_zps0da25836.jpg");
</script>
</html>